config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index, :destroy]

  resources :sneakers, only: [:index, :show, :create, :update] do
    resources :reviews, only: [:new, :create, :index]
  end

  namespace :admin do
    resources :sneakers, only: [:new, :edit, :destroy]
    resources :brands, only: [:new, :edit, :destroy]
    resources :sports, only: [:new, :edit, :destroy]
  end

  resources :brands do
    resources :sneakers, only: [:index]
  end

  resources :sports do
    resources :sneakers, only: [:index]
  end

  resources :home, only: [:index]

  get '/sports/:id/brands', to: 'sports#brands', as: 'sport_brands'
  get '/brands/:id/sports', to: 'brands#sports', as: 'brand_sports' 

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'home#index'
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :sneakers
  has_and_belongs_to_many :brands
  validates :name, presence: true, uniqueness: true
  validates :image_url, presence: true

  def my_brands
    ids = sneakers.pluck(:brand_id).uniq
    Brand.find(ids)
  end
end

app/controllers/admin/sports_controller.rb
class Admin::SportsController < Admin::MasterController
  before_action :set_sport, only: [:edit, :destroy]

  def new
    @sport = Sport.new
    @brands = Brand.all
    @sneakers = Sneaker.all
  end

  def edit
    @sneakers = Sneaker.all
    @brands = Brand.all
    @is_admin = current_admin?
  end

  def destroy
    @sport.destroy
    flash[:delete] = "#{@sport.name} deleted"
    redirect_to sports_path
  end

  private

  def set_sport
    @sport = Sport.find(params[:id])
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :update, :brands]
  # before_action :get_sports, only: [:index]

  def index
    @sports = Sport.all
    @is_admin = current_admin?
  end

  def create
    @sport = Sport.new(sport_params)
    if @sport.save
      flash[:success] = "#{@sport.name} created"
      redirect_to @sport
    else
      render :'admin/sports/new'
    end
  end

  def show
    @sneakers = @sport.sneakers
    @is_admin = current_admin?
  end

  def update
    if @sport.update(sport_params)
      flash[:success] = "#{@sport.name} updated!"
      redirect_to @sport
    else
      render :edit
    end
  end

  def brands
    @brands = @sport.my_brands
    render :'/brands/index'
  end


  private

  def sport_params
    params.require(:sport).permit(:name, :image_url, brand_ids: [])
  end

  def set_sport
    @sport = Sport.find(params[:id])
  end
end

app/views/sports/index.html.erb
<h1> List of Sports </h1>

<% unless @sports.nil? %>
  <% @sports.each do |sport| %>
    <ul class="displays">
      <li class="display_list">
        <%= image_tag sport.image_url, :class => "sport_logo" %>
          <%= link_to sport.name, sport %>
          <% if @is_admin %>
            <%= link_to "Edit", edit_admin_sport_path(sport) %>
            <%= link_to "Delete", admin_sport_path(sport), method: :delete %>
          <% end %>
        </li>
      </ul>
  <% end %>
<% end %>

  <% if @is_admin %>
    <%= link_to "Create New Sport", new_admin_sport_path %>
  <% end %>

app/views/sports/show.html.erb
<% if from_nest? %>
  <% @sport.sneakers.each do |sneaker| %>
    <ul class="displays">
      <li class="display_list">
        <%= image_tag sneaker.image_url, :class => "sneaker_image" %>
        <%= link_to sneaker.name, sneaker %>
        <%= link_to "Additional Info", sneaker %>
        <% if @is_admin %>
          <%= link_to "Edit", edit_admin_sneaker_path(sneaker) %>
          <%= link_to "Delete", admin_sneaker_path(sneaker), method: :delete %>
        <% end %>
      </li>
    </ul>
  <% end %>
<% else %>
  <h1><%="#{@sport.name}"%></h1>

  <h2><%=image_tag @sport.image_url, :class => "sport_logo"%></h2>

  <%= link_to "Kicks by #{@sport.name}!", sport_sneakers_path(@sport) %>

  <%= link_to "View by Brand for #{@sport.name}!", sport_brands_path(@sport) %>


  <% if @is_admin %>
    <%= link_to "Edit", edit_admin_sport_path(@sport) %>
    <%= link_to "Delete", admin_sport_path(@sport), method: :delete %>
  <% end %>
<% end %>