config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index, :destroy]

  resources :sneakers, only: [:index, :show, :create, :update] do
    resources :reviews, only: [:new, :create, :index]
  end

  namespace :admin do
    resources :sneakers, only: [:new, :edit, :destroy]
    resources :brands, only: [:new, :edit, :destroy]
    resources :sports, only: [:new, :edit, :destroy]
  end

  resources :brands do
    resources :sneakers, only: [:index]
  end

  resources :sports do
    resources :sneakers, only: [:index]
  end

  resources :home, only: [:index]

  get '/sports/:id/brands', to: 'sports#brands', as: 'sport_brands'
  get '/brands/:id/sports', to: 'brands#sports', as: 'brand_sports' 

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @new_releases = Sneaker.new_releases
  end
end

app/views/home/index.html.erb
<h1> Welcome to Diet Foot Locker! </h1>

<ul class="displays">
  <li class="display_list">
    <%= image_tag "diet_foot_locker.png" %>
  </li>

    <%= link_to "View all Sneakers", sneakers_path %>
    <%= link_to "View all Brands", brands_path %>
    <%= link_to "View all Sports", sports_path %>

  <li class="home_login">
    <%= link_to "Login", login_path %>
  </li>
    <div> OR </div>
  <li class="home_login">
    <%= link_to "Create New Account", new_user_path %>
  </li>
</ul>

<% unless @new_releases.nil? %>
  <h1> New Releases </h1>
  <% @new_releases.each do |release| %>
    <ul class="displays">
      <li class="display_list">
        <%=image_tag release.image_url, :class => "sneaker_image"%>
        <%= link_to release.name, release %>
        <%= link_to "Additional Info", release %>
      </li>
    </ul>
  <% end %>
<% end %>