config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index, :destroy]

  resources :sneakers, only: [:index, :show, :create, :update] do
    resources :reviews, only: [:new, :create, :index]
  end

  namespace :admin do
    resources :sneakers, only: [:new, :edit, :destroy]
    resources :brands, only: [:new, :edit, :destroy]
    resources :sports, only: [:new, :edit, :destroy]
  end

  resources :brands do
    resources :sneakers, only: [:index]
  end

  resources :sports do
    resources :sneakers, only: [:index]
  end

  resources :home, only: [:index]

  get '/sports/:id/brands', to: 'sports#brands', as: 'sport_brands'
  get '/brands/:id/sports', to: 'brands#sports', as: 'brand_sports' 

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'home#index'
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :sneakers
  has_and_belongs_to_many :sports
  validates :name, presence: true, uniqueness: true
  validates :image_url, presence: true

  def new_releases
    Sneaker.where(brand_id: id)[-3..-1]
  end

  def my_sports
    ids = sneakers.pluck(:sport_id).uniq
    Sport.find(ids)
  end
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::MasterController
  before_action :set_brand, only: [:edit, :destroy]

  def new
    @brand = Brand.new
    @sports = Sport.all
  end

  def edit
    @sneakers = Sneaker.all
    @sports = Sport.all
  end

  def destroy
    @brand.destroy
    flash[:delete] = "#{@brand.name} deleted"
    redirect_to brands_path
  end

  private

  def set_brand
    @brand = Brand.find(params[:id])
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :update, :sports]
  # before_action :get_brands, only: [:index]

  def index
    @brands = Brand.all
    @is_admin = current_admin?
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      flash[:success] = "#{@brand.name} created"
      redirect_to @brand
    else
      render :'admin/brands/new'
    end
  end

  def show
    @sneakers = @brand.sneakers
    @new_releases = @brand.new_releases
    @is_admin = current_admin?
  end

  def update
    if @brand.update(brand_params)
      flash[:success] = "#{@brand.name} updated!"
      redirect_to @brand
    else
      render :edit
    end
  end

  def sports
    @sports = @brand.my_sports
    render :'/sports/index'
  end

  private

  def brand_params
    params.require(:brand).permit(:name, :image_url, sport_ids: [])
  end

  def set_brand
    @brand = Brand.find(params[:id])
  end
end

app/views/brands/index.html.erb
<h1> List of Brands </h1>

<% @brands.each do |brand| %>
  <ul class="displays">
    <li class="display_list">
      <%= image_tag brand.image_url, :class => "brand_logo" %>
      <%= link_to brand.name, brand %>
      <% if @is_admin %>
        <%= link_to "Edit", edit_admin_brand_path(brand) %>
        <%= link_to "Delete", admin_brand_path(brand), method: :delete %>
      <% end %>
    </li>
  </ul>
<% end %>

  <% if @is_admin %>
    <%= link_to "Create New Brand", new_admin_brand_path %>
  <% end %>

app/views/brands/show.html.erb
<% if from_nest? %>
  <% @sport.sneakers.each do |sneaker| %>
    <ul class="displays">
      <li class="display_list">
        <%= image_tag sneaker.image_url, :class => "sneaker_image" %>
        <%= link_to sneaker.name, sneaker %>
        <%= link_to "Additional Info", sneaker %>
        <% if @is_admin %>
          <%= link_to "Edit", edit_admin_sneaker_path(sneaker) %>
          <%= link_to "Delete", admin_sneaker_path(sneaker), method: :delete %>
        <% end %>
      </li>
    </ul>
  <% end %>

<% else %>
  <h1><%="#{@brand.name}"%></h1>

  <h2 ><%=image_tag @brand.image_url, :class => "brand_logo"%></h2>

  <%= link_to "Kicks by #{@brand.name}!", brand_sneakers_path(@brand) %>

  <%= link_to "View by Sport for #{@brand.name}!", brand_sports_path %>

  <% if @is_admin %>
    <%= link_to "Edit", edit_admin_brand_path(@brand) %>
    <%= link_to "Delete", admin_brand_path(@brand), method: :delete %>
  <% end %>

  <% unless @new_releases.nil? %>
    <h2> Newest Releases </h2>
      <% @new_releases.each do |release| %>
        <ul class="displays">
          <li class="display_list">
            <%=image_tag release.image_url, :class => "sneaker_image"%>
            <%= link_to release.name, release %>
            <%= link_to "Additional Info", release %>
          </li>
        </ul>
      <% end %>
  <% end %>

  <% unless @sports.nil? %>
    <% @sports.each do |sport| %>
      <ul class="displays">
        <li class="display_list">
          <%= sport.name %>
        </ul>
      </li>
    <% end %>
  <% end %>

<% end %>