config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index, :destroy]

  resources :sneakers, only: [:index, :show, :create, :update] do
    resources :reviews, only: [:new, :create, :index]
  end

  namespace :admin do
    resources :sneakers, only: [:new, :edit, :destroy]
    resources :brands, only: [:new, :edit, :destroy]
    resources :sports, only: [:new, :edit, :destroy]
  end

  resources :brands do
    resources :sneakers, only: [:index]
  end

  resources :sports do
    resources :sneakers, only: [:index]
  end

  resources :home, only: [:index]

  get '/sports/:id/brands', to: 'sports#brands', as: 'sport_brands'
  get '/brands/:id/sports', to: 'brands#sports', as: 'brand_sports' 

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'home#index'
end

app/models/sneaker.rb
class Sneaker < ApplicationRecord
  has_many :reviews
  belongs_to :brand
  belongs_to :sport
  has_and_belongs_to_many :users

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image_url, presence: true
  validates :footlocker_url, presence: true

  def self.new_releases
    Sneaker.all[-2..-1]
  end
end

app/controllers/admin/sneakers_controller.rb
class Admin::SneakersController < Admin::MasterController
  before_action :set_sneaker, only: [:edit, :destroy]

  def new
    @sneaker = Sneaker.new
  end

  def edit
  end

  def destroy
    @sneaker.destroy
    flash[:delete] = "#{@sneaker.name} deleted"
    redirect_to sneakers_path
  end

  private

  def set_sneaker
    @sneaker = Sneaker.find(params[:id])
  end
end

app/controllers/sneakers_controller.rb
class SneakersController < ApplicationController
  before_action :set_sneaker, only: [:show, :update]
  before_action :get_sneakers, only: [:index]

  def index
    @is_admin = current_admin?
  end

  def show
    @sneaker = Sneaker.find(params[:id])
    # @is_admin = current_admin?
    @review = @sneaker.reviews.new
  end

  def create
    @sneaker = Sneaker.new(sneaker_params)
    if @sneaker.save
      flash[:success] = "#{@sneaker.name} created"
      redirect_to @sneaker
    else
      render :'admin/sneakers/new'
    end
  end

  def update
    if @sneaker.update(sneaker_params)
      flash[:success] = "#{@sneaker.name} updated!"
      redirect_to @sneaker
    else
      render :edit
    end
  end

  private

  def set_sneaker
    @sneaker = Sneaker.find(params[:id])
  end

  def sneaker_params
    params.require(:sneaker).permit(:name, :description, :image_url,
                                    :price, :footlocker_url,
                                    :brand_id, :sport_id)
  end
end

app/helpers/sneakers_helper.rb
module SneakersHelper
end

app/views/sneakers/_review.html.erb
<div>
  <% unless review.user.nil? %>
    <h4>Review by <%= review.user.username %></h4>
    <p class="review"><%= review.body %></a>
    <p>Posted <%= review.post_date %></p>
  <% end %>
</div>

app/views/sneakers/index.html.erb
<h1> List of Sneakers </h1>

<% @sneakers.each do |sneaker| %>
  <ul class="displays">
    <li class="display_list">
      <%= image_tag sneaker.image_url, :class => "sneaker_image" %>
      <%= link_to sneaker.name, sneaker %>
      <%= link_to "Additional Info", sneaker %>
      <% if @is_admin %>
        <%= link_to "Edit", edit_admin_sneaker_path(sneaker) %>
        <%= link_to "Delete", admin_sneaker_path(sneaker), method: :delete %>
      <% end %>
    </li>
  </ul>
<% end %>

  <% if @is_admin %>
    <%= link_to "Create New Shoe", new_admin_sneaker_path %>
  <% end %>

app/views/sneakers/show.html.erb
<h1><%="#{@sneaker.name}"%></h1>

<h2><%=image_tag @sneaker.image_url, :class => "sneaker_image"%></h2>

<ul class="displays">
  <li class="display_list"><%=@sneaker.name %></li>
  <li class="display_list"><%=@sneaker.description %></li>
  <li class="display_list">Price: $<%=@sneaker.price %></li>
  <li class="display_list"><%=link_to "Buy Now", @sneaker.footlocker_url%></li>
</ul>

<% if @is_admin %>
  <%= link_to "Edit", edit_admin_sneaker_path(@sneaker) %>
  <%= link_to "Delete", admin_sneaker_path(@sneaker), method: :delete %>
<% end %>

<%= render partial: 'reviews/form' %>

<h3>Reviews (<%= @sneaker.reviews.size - 1 %>)</h3>
<%= render partial: 'sneakers/review', collection: @sneaker.reviews.reverse %>